
GROQ_API_KEY="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"
OPENAI_API_KEY="sk-proj-QZTcQ80LhwXz9nZaYiF-SMDK-VAejxiidDHfntx575a-kfVGszeGBsEX9ttaQ86-ZjBinWcMW7T3BlbkFJJ125lbsnUCgJZlqglwclSCkEOO7To1WQBfkySibqUANAUwHMOsRWb6QEmZpkHD69zgdJ_Krt4Aa"
GEMINI_API_KEY="AIzaSyBy-fdXVfBhzVcJgPF6RP6Dz-RlsZB56cg"